name: GitHub Release

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  release:
    name: Release native binaries
    permissions:
      id-token: write
      attestations: write
      artifact-metadata: write
      contents: write
    strategy:
      matrix:
        kind: [ 'linux-arm64' ]
        include:
          - kind: linux-arm64
            os: ubuntu-24.04-arm
            target: linux-arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup dotnet
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: 10.0.x

      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          date=$(date -u +"%Y-%m-%d")
          ASSEMBLY_VERSION="${tag//v}"
          jq --arg version "$ASSEMBLY_VERSION" --arg date "$date" \
            '.version = $version | .release_date = $date' \
            src/UnfoldedCircle.SystemMonitor/driver.json > tmp.json && mv tmp.json src/UnfoldedCircle.SystemMonitor/driver.json
          
          # Build everything
          release_name="unfolded-circle-system-monitor-$tag-${{ matrix.kind }}"
          
          dotnet restore "./src/UnfoldedCircle.SystemMonitor/UnfoldedCircle.SystemMonitor.csproj" --locked-mode -p:PublishAot=true
          dotnet publish "./src/UnfoldedCircle.SystemMonitor/UnfoldedCircle.SystemMonitor.csproj" -r ${{ matrix.target }} -c Release -o ./publish -p:Version="$ASSEMBLY_VERSION" -p:PublishAot=true --no-restore
          if [ "${{ matrix.target }}" == "linux-arm64" ]; then
            mkdir driverdir && mkdir driverdir/bin && mkdir driverdir/config && mkdir driverdir/data
            cp publish/driver.json driverdir/driver.json
            cp publish/appsettings*.json driverdir/bin/
          
            cp publish/driver driverdir/bin/
            cp publish/driver.dbg driverdir/bin/
          
            tar -czvf unfolded-circle-system-monitor-$tag-remote.tar.gz -C ./driverdir .
          
            # Delete output directory
            rm -r "./driverdir"
          fi
          
          # Delete output directory
          rm -r "./publish"

      - name: Publish
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          files: |
            unfolded-circle-system-monitor*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Attest build provenance
        uses: actions/attest@f7c74d28b9d84cb8768d0b8ca14a4bac6ef463e6 # v4.2.0
        with:
          subject-path: |
            unfolded-circle-system-monitor*.tar.gz
